-- USER SQL
CREATE USER joeweb IDENTIFIED BY joeweb123 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "CONNECT" TO joeweb ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO joeweb;
GRANT GRANT ANY PRIVILEGE TO joeweb;
GRANT CREATE SEQUENCE TO joeweb;
GRANT CREATE TABLE TO joeweb;
GRANT CREATE VIEW TO joeweb;
GRANT CREATE TYPE TO joeweb ;
GRANT ALTER ANY INDEX TO joeweb ;
GRANT GRANT ANY OBJECT PRIVILEGE TO joeweb ;
GRANT UNLIMITED TABLESPACE TO joeweb ;
GRANT GRANT ANY ROLE TO joeweb ;
GRANT CREATE PROCEDURE TO joeweb ;

