--------------------------------------------------------
--  File created - Friday-October-25-2013   
--------------------------------------------------------
REM INSERTING into CLPB_EMPRESA_AFILIADORA
SET DEFINE OFF;
Insert into CLPB_EMPRESA_AFILIADORA (ID,CO_USUARIO_CREADOR,CO_USUARIO_MODIFICADOR,DA_FECHA_CREACION,DA_FECHA_MODIFICACION,DE_EMPRESA_AFILIADORA,ST_EMPRESA_AFILIADORA,CO_PROGRAMA) values (1,'dkuyeng','bflores',to_timestamp('31-OCT-11 08.07.39.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('03-OCT-13 12.05.32.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'Gold Import','Y',3690);
