--------------------------------------------------------
--  File created - Friday-October-25-2013   
--------------------------------------------------------
REM INSERTING into ROLE
SET DEFINE OFF;
Insert into ROLE (ID,DESCRIPTION,NAME) values (1,'Rol de afiliadoras con permiso para activar tarjetas.1','ROLE_PLUS_USER');
Insert into ROLE (ID,DESCRIPTION,NAME) values (2,'Rol para el area de marketing','ROLE_MARKETING');
Insert into ROLE (ID,DESCRIPTION,NAME) values (6881,'Rol para Logistica','ROLE_LOGISTICA');
Insert into ROLE (ID,DESCRIPTION,NAME) values (307890,'Liquidacion Programas','ROLE_LIQUIDACION');
Insert into ROLE (ID,DESCRIPTION,NAME) values (408490,'Rol para las pruebas de desarrollador en producción','ROL_DEVELOPER');
Insert into ROLE (ID,DESCRIPTION,NAME) values (424300,'Rol para el area de tesorería','ROLE_TESORERIA');
Insert into ROLE (ID,DESCRIPTION,NAME) values (4,'Rol para el area de Flotas','ROLE_FLOTAS');
Insert into ROLE (ID,DESCRIPTION,NAME) values (289880,'Canje de Premios','ROLE_CANJE');
Insert into ROLE (ID,DESCRIPTION,NAME) values (-2,'Rol por defecto para todos los usuarios','ROLE_USER');
Insert into ROLE (ID,DESCRIPTION,NAME) values (-1,'Rol Administradorde del sistema (Puede editar usuarios)','ROLE_ADMIN');
Insert into ROLE (ID,DESCRIPTION,NAME) values (296690,'Rol para manejo de línea de crédito para flotas','ROLE_LINEA_CREDITO');
